// <auto-generated />
using System;
using HawksMusic.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HawksMusic.API.Migrations
{
    [DbContext(typeof(HawksDataContext))]
    [Migration("20231117181843_Correção tabela usuarios")]
    partial class Correçãotabelausuarios
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.10");

            modelBuilder.Entity("HawksMusic.API.Models.AlbumModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AnoLancamento")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Artista")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Gravadora")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Albums");
                });

            modelBuilder.Entity("HawksMusic.API.Models.MusicaModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("AlbumModelId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Arquivo")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int?>("PlayListModelId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("AlbumModelId");

                    b.HasIndex("PlayListModelId");

                    b.ToTable("Musicas");
                });

            modelBuilder.Entity("HawksMusic.API.Models.PlayListModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("PlayLists");
                });

            modelBuilder.Entity("HawksMusic.API.Models.UsuarioModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<int?>("PlayListModelId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PlayListModelId");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("HawksMusic.API.Models.MusicaModel", b =>
                {
                    b.HasOne("HawksMusic.API.Models.AlbumModel", "Album")
                        .WithMany()
                        .HasForeignKey("AlbumModelId");

                    b.HasOne("HawksMusic.API.Models.PlayListModel", null)
                        .WithMany("Musicas")
                        .HasForeignKey("PlayListModelId");

                    b.Navigation("Album");
                });

            modelBuilder.Entity("HawksMusic.API.Models.UsuarioModel", b =>
                {
                    b.HasOne("HawksMusic.API.Models.PlayListModel", "PlayList")
                        .WithMany()
                        .HasForeignKey("PlayListModelId");

                    b.Navigation("PlayList");
                });

            modelBuilder.Entity("HawksMusic.API.Models.PlayListModel", b =>
                {
                    b.Navigation("Musicas");
                });
#pragma warning restore 612, 618
        }
    }
}
